---
title: "Security Council Membership"
author: "Evangeline Reynolds"
date: "12/21/2017"
output: html_document
---



I get the UN Security Council data from the UN's website "Countries Elected Members of the Security Council", \url{https://www.un.org/securitycouncil/content/countries-elected-members}


```{r}
if (!dir.exists("raw_data")) {
  dir.create("raw_data")
}

if (!file.exists("raw_data/sc_members_elected_2019-01-22.txt"))  {
  download.file("https://www.un.org/securitycouncil/content/countries-elected-members",
                destfile = paste0("raw_data/sc_members_elected_", 
                                Sys.Date(), ".txt"))
}

```

```{r, message=FALSE, warning=F}
text0 <- readLines("raw_data/sc_members_elected_2019-01-22.txt", 
                   encoding = "UTF-8")
text1 <- text0[grep(text0, pattern = "\\<p\\>")]
text1 <- text1[2:length(text1)]
text1[1] <- "Algeria"  # regular expressions cannot save us here

library(tidyverse)
security_council_non_permanent <- data_frame(text1) %>% 
  mutate(text1 = 
           str_replace_all(text1, "\\<p\\>|\\<\\/p\\>|\\<br \\/\\>", "")) %>% 
  mutate(year = lead(text1)) %>% 
  rename(country = text1) %>% 
  filter(!str_detect(country, "^\\d")) %>% 
  filter(!str_detect(year, "^\\D")) %>% 
  mutate(year = str_split(year, " , ")) %>% 
  unnest() %>% 
  group_by(country) %>% 
  mutate(which_tenure = 1:n()) %>% 
  mutate(year = str_split(year, " – ")) %>% 
  unnest() %>% 
  mutate(year = str_extract(year, "\\d{4}")) %>% 
  mutate(year = as.numeric(year)) %>%
  group_by(country, which_tenure) %>% 
  mutate(year_of_tenure = 1:n()) %>% 
  filter(year <= 2019)
  
```


# Check Saudi Arabia
```{r}
# Place holder - are the dates for actual seating?  Declined to take seat. 
```

# Yemen 

Yemen has a slightly different format, so the regular expressions fail. We add it here.


```{r}
yemen <-  data_frame(country = rep("Yemen", 2),
                     which_tenure = rep(1, 2),
                     year = 1990:1991,
                     year_of_tenure = 1:2)

security_council_non_permanent <-  
  bind_rows(security_council_non_permanent, yemen) %>% 
  arrange(country)
```




One Case missing - add it (East Germany)
----

```{r}
east_germany <- data_frame(country = rep("East Germany", 2), 
                   which_tenure = rep(1, 2), 
                   year = 1980:1981,
                   year_of_tenure = 1:2)

security_council_non_permanent <-  
  bind_rows(security_council_non_permanent, east_germany) %>% 
  arrange(country)

```

```{r}
ggplot(data = security_council_non_permanent %>% group_by(year) %>% tally()) +
  aes(year, n) +
  geom_col(alpha = .2, fill = "magenta") 

```


# Save product
```{r}
if (!dir.exists("product_data")) {
  dir.create("product_data")
}

write_csv(security_council_non_permanent, "product_data/security_council_non_permanent.csv")

save(security_council_non_permanent,
     file = "product_data/security_council_non_permanent.Rdata")

save(security_council_non_permanent, file = "../data/security_council_membership.rda")
```

# session info

```{r}
sessionInfo()
```



